services:
  - type: web
    name: ideareactor-web
    runtime: python
buildCommand: |
  pip install --force-reinstall certifi
  poetry install
  playwright install  # only for the web service
    startCommand: gunicorn kofi_webhook:app
    envVars:
      - key: KOFI_VERIFICATION_TOKEN
        sync: true
      - key: EMAIL_USER
        sync: true
      - key: EMAIL_PASS
        sync: true
      - key: GUMROAD_EMAIL
        sync: true
      - key: GUMROAD_PASSWORD
        sync: true
      - key: SHOPIFY_STORE
        sync: true
      - key: SHOPIFY_API_KEY
        sync: true
      - key: SHOPIFY_PASSWORD
        sync: true

  - type: worker
    name: ideareactor-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_pipeline.py
    envVars:
      - key: GUMROAD_ACCESS_TOKEN
        sync: true
      - key: PRODUCT_HUNT_CLIENT_ID
        sync: true
      - key: PRODUCT_HUNT_API_SECRET
        sync: true
      - key: PRODUCT_HUNT_REDIRECT_URI
        sync: true
      - key: YOUTUBE_API_KEY
        sync: true
      - key: TECHCRUNCH_RSS_URL
        sync: true
      - key: POLYGON_API_KEY
        sync: true
      - key: MISTRAL_API_URL
        sync: true
