name: Run IdeaReactor Pipeline

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the pipeline
        env:
          MISTRAL_API_URL: ${{ secrets.MISTRAL_API_URL }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          # Add any other secrets your script uses
        run: |
          python run_pipeline.py
